saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.OrderListView.as_view(), name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group')]

saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import api
from . import views


urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^add/$',
        views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_edit, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/bulk_delete/',
        views.variants_bulk_delete, name='variant-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/$',
        views.stock_edit, name='product-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/stock/add/$',
        views.stock_edit, name='product-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='product-stock-delete'),
    url(r'^(?P<product_pk>[0-9]+)/stock/bulk_delete/',
        views.stock_bulk_delete, name='stock-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_edit, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),
    url('^(?P<product_pk>[0-9]+)/images/reorder/$',
        api.reorder_product_images, name='product-images-reorder'),
    url('^(?P<product_pk>[0-9]+)/images/upload/$',
        api.upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/add/$',
        views.attribute_edit, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),
]

saleor/dashboard/shipping/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.shipping_method_list, name='shipping-methods'),
    url(r'^add/$', views.shipping_method_add, name='shipping-method-add'),
    url(r'^(?P<pk>\d+)/$', views.shipping_method_detail, name='shipping-method-detail'),
    url(r'^(?P<pk>\d+)/delete/$',
        views.shipping_method_delete, name='shipping-method-delete'),
]

saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .order.urls import urlpatterns as order_urls
from .payments.urls import urlpatterns as payments_urls
from .product.urls import urlpatterns as product_urls
from .discount.urls import urlpatterns as discount_urls
from .shipping.urls import urlpatterns as shipping_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^payments/', include(payments_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^shipping/', include(shipping_urls)),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .dashboard.urls import urlpatterns as dashboard_urls


admin.autodiscover()

urlpatterns = [
    url(r'^', include(core_urls, namespace="core")),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^account/', include(registration_urls, namespace='registration')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT})]

saleor/dashboard/category/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from unidecode import unidecode

from ...product.models import Category


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.parent_pk = kwargs.pop('parent_pk')
        super(CategoryForm, self).__init__(*args, **kwargs)
        if self.instance.parent and self.instance.parent.hidden:
            self.fields['hidden'].widget.attrs['disabled'] = True

    class Meta:
        model = Category
        exclude = ['slug']

    def save(self, commit=True):
        self.instance.slug = slugify(unidecode(self.instance.name))
        if self.parent_pk:
            self.instance.parent = get_object_or_404(
                Category, pk=self.parent_pk)
        if self.instance.parent and self.instance.parent.hidden:
            self.instance.hidden = True
        super(CategoryForm, self).save(commit=commit)
        self.instance.set_hidden_descendants(self.cleaned_data['hidden'])
        return self.instance

saleor/checkout/views/shipping.py
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from ..forms import AnonymousUserShippingForm, ShippingAddressesForm
from ...userprofile.forms import AddressForm
from ...userprofile.models import Address


def anonymous_user_shipping_address_view(request, checkout):
    data = request.POST or None
    shipping_address = checkout.shipping_address
    if shipping_address is not None:
        address_form = AddressForm(
            data, instance=checkout.shipping_address, autocomplete_type='shipping')
    else:
        address_form = AddressForm(
            data, autocomplete_type='shipping', initial={'country': request.country})
    user_form = AnonymousUserShippingForm(data, initial={'email': checkout.email})
    if user_form.is_valid() and address_form.is_valid():
        checkout.shipping_address = address_form.instance
        checkout.email = user_form.cleaned_data['email']
        return redirect('checkout:shipping-method')
    return TemplateResponse(
        request, 'checkout/shipping_address.html', context={
            'address_form': address_form, 'user_form': user_form, 'checkout': checkout})


def user_shipping_address_view(request, checkout):
    data = request.POST or None
    additional_addresses = request.user.addresses.all()
    checkout.email = request.user.email
    shipping_address = checkout.shipping_address

    if shipping_address is not None and shipping_address.id:
        address_form = AddressForm(
            data, autocomplete_type='shipping', initial={'country': request.country})
        addresses_form = ShippingAddressesForm(
            data, additional_addresses=additional_addresses,
            initial={'address': shipping_address.id})
    elif shipping_address:
        address_form = AddressForm(data, instance=shipping_address)
        addresses_form = ShippingAddressesForm(
            data, additional_addresses=additional_addresses)
    else:
        address_form = AddressForm(data, initial={'country': request.country})
        addresses_form = ShippingAddressesForm(
            data, additional_addresses=additional_addresses)

    if addresses_form.is_valid():
        if addresses_form.cleaned_data['address'] != ShippingAddressesForm.NEW_ADDRESS:
            address_id = addresses_form.cleaned_data['address']
            checkout.shipping_address = Address.objects.get(id=address_id)
            return redirect('checkout:shipping-method')
        elif address_form.is_valid():
            checkout.shipping_address = address_form.instance
            return redirect('checkout:shipping-method')
    return TemplateResponse(
        request, 'checkout/shipping_address.html', context={
            'address_form': address_form, 'user_form': addresses_form,
            'checkout': checkout, 'additional_addresses': additional_addresses})

saleor/dashboard/category/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from ...product.models import Category
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
def category_list(request, root_pk=None):
    root = None
    path = None
    categories = Category.tree.root_nodes()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
        categories = root.get_children()
    ctx = {'categories': categories, 'path': path, 'root': root}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
def category_create(request, root_pk=None):
    category = Category()
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
def category_edit(request, root_pk=None):
    category = get_object_or_404(Category, pk=root_pk)
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status}
    template = 'dashboard/category/modal_edit.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(request, _('Deleted category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-list', kwargs={'root_pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(request,
                            'dashboard/category/modal_delete.html',
                            ctx)

saleor/dashboard/customer/views.py
from __future__ import unicode_literals

from django.db.models import Count, Max
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from .forms import CustomerSearchForm
from ..views import staff_member_required
from ...core.utils import get_paginator_items
from ...userprofile.models import User


@staff_member_required
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .annotate(
            num_orders=Count('orders', distinct=True),
            last_order=Max('orders', distinct=True)))

    form = CustomerSearchForm(request.GET or None, queryset=customers)
    form_values = [(field.name, field.value() or '') for field in form]
    if form.is_valid():
        customers = form.search()
    else:
        customers = customers.filter(
            orders__status__in=['new', 'payment-pending', 'fully-paid'])
    title = _('Results (%s)') % len(customers)

    customers = get_paginator_items(customers, 30, request.GET.get('page'))
    ctx = {'customers': customers, 'form': form, 'title': title,
           'default_pagination_params': form_values}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related('default_billing_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)

saleor/dashboard/payments/views.py
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.views.generic import ListView
from payments.models import PAYMENT_STATUS_CHOICES

from ..views import (FilterByStatusMixin, StaffMemberOnlyMixin,
                     staff_member_required)
from ...order.models import Payment
from ..order.forms import PaymentFilterForm


class PaymentList(StaffMemberOnlyMixin, FilterByStatusMixin, ListView):
    model = Payment
    template_name = 'dashboard/payments/list.html'
    context_object_name = 'payments'
    paginate_by = 30
    form_class = PaymentFilterForm
    status_choices = PAYMENT_STATUS_CHOICES
    status_order = ['waiting', 'input', 'preauth', 'confirmed', 'refunded',
                    'rejected', 'error']

    def get_queryset(self):
        qs = super(PaymentList, self).get_queryset()
        return qs.order_by('-created').select_related('order')


@staff_member_required
def payment_details(request, pk):
    payment = get_object_or_404(Payment, pk=pk)
    return TemplateResponse(request, 'dashboard/payments/detail.html',
                            {'payment': payment})

saleor/dashboard/templates/dashboard/shipping/method_delete.html
{% extends "dashboard/base.html" %}
{% load materializecss %}
{% load i18n %}

{% block title %}{% trans "Delete" %} {{ shipping_method }}{% endblock %}

{% block body_class %}body-shipping-methods{% endblock %}

{% block page_title %}{% trans "Delete" %} {{ shipping_method }}{% endblock %}

{% block menu_delivery_class %}active{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:shipping-methods' %}"
               class="breadcrumbs--ellipsed-item">{% trans "Subscription methods" %}</a>
        </li>
        <li><a href="{% url 'dashboard:shipping-method-detail' pk=shipping_method.pk %}"
               class="breadcrumbs--ellipsed-item">{{ shipping_method }}</a>
        </li>
        <li>
            <span class="breadcrumbs--ellipsed-item">{% trans "Delete" %}</span>
        </li>
    </ul>
{% endblock %}

{% block menu_shipping_class %} active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col s12 m5">
            <div class="card-panel">
              {% blocktrans with shipping_method_name=shipping_method %}
              Are you sure you want to delete the {{ shipping_method_name }} method?
              {% endblocktrans %}
            </div>
        </div>
    </div>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn red">{% trans "Delete" %}</button>
        </div>
    </form>
{% endblock %}

saleor/dashboard/templates/dashboard/shipping/method_form.html
{% extends "dashboard/base.html" %}
{% load materializecss %}
{% load i18n %}
{% load mptt_tags %}


{% block title %}
    {% trans "Shipping methods" %}
    {% if shipping_method.pk %}
        - {{ shipping_method }}
    {% else %}
        - {% trans 'Add new method' %}
    {% endif %}
    - {{ block.super }}
{% endblock %}

{% block body_class %}body-shipping-methods{% endblock %}

{% block menu_delivery_class %}active{% endblock %}

{% block page_title %}{% if shipping_method.pk %}{{ shipping_method }}{% else %}
    {% trans 'Add new method' %}
{% endif %}{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:shipping-methods' %}"
               class="breadcrumbs--ellipsed-item">{% trans "Shipping methods" %}</a>
        </li>
        <li>
            {% if shipping_method.pk %}
                <span class="breadcrumbs--ellipsed-item">{{ shipping_method }}</span>
            {% else %}
                <span class="breadcrumbs--ellipsed-item">{% trans 'Add new method' %}</span>
            {% endif %}
        </li>
    </ul>
{% endblock %}

{% block menu_shipping_class %} active{% endblock %}

{% block content %}
    <form method="post" id="form-method">
        {% csrf_token %}
        {{ price_per_country_formset.management_form }}
        <div class="row">
            {{ shipping_method_form|materializecss }}
        </div>
        <h4 class="light">{% trans "Price per country" %}</h4>

        <div class="card-panel">
            {% for form in price_per_country_formset %}
                <div class="row">
                    {{ form.id }}
                    {{ form.country_code|materializecss:"input-field s12 l6" }}
                    {{ form.price|materializecss:"input-field s12 l5" }}
                    {{ form.DELETE|materializecss:"input-field s12 l1" }}
                </div>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="help-block materialize-red-text">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </div>


        <div class="row">
            {% if shipping_method.pk %}
                <div class="col s12 l6">
                    <a href="{% url 'dashboard:shipping-method-delete' pk=shipping_method.pk %}"
                       class="btn red">{% trans "Delete" %}</a>
                </div>
                <div class="col s12 l6 right-align">
                    <a href="{% url 'dashboard:shipping-methods' %}"
                       class="btn-flat">{% trans "Cancel" %}</a>
                    <button type="submit" class="btn">{% trans "Update" %}</button>
                </div>
            {% else %}
                <div class="col s12 right-align">
                    <a href="{% url 'dashboard:shipping-methods' %}"
                       class="btn-flat">{% trans "Cancel" %}</a>
                    <button type="submit" class="btn">{% trans "Create" %}</button>
                </div>
            {% endif %}
        </div>
    </form>
{% endblock %}

saleor/dashboard/templates/dashboard/shipping/method_list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load prices_i18n %}
{% load status %}

{% block title %}{% trans "Shipping methods" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-shipping-methods{% endblock %}

{% block menu_delivery_class %}active{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs">
        <li>{% trans "Shipping" %}</li>
        <li>{% trans "methods" %}</li>
    </ul>
{% endblock %}

{% block header_extra %}
    <div class="fixed-action-btn">
        <a class="btn-fab btn-floating btn-large waves-effect waves-light teal"
           title="{% trans "Add method" %}"
           href="{% url 'dashboard:shipping-method-add' %}">
            <i class="mdi-content-add"></i>
        </a>
    </div>
{% endblock %}

{% block content %}
    {% if shipping_methods %}
        <div class="card">
            <div class="data-table-container">
                <table class="bordered hoverable responsive data-table">
                    <thead>
                    <tr>
                        <th>{% trans "Name" %}</th>
                        <th>{% trans "Price range" %}</th>
                        <th class="wide">{% trans "Countries" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for method in shipping_methods %}
                        <tr>
                            <td>
                                <a href="{% url 'dashboard:shipping-method-detail' pk=method.pk %}">{{ method }}</a>
                            </td>
                            <td>
                                {% if not method.price_range %}
                                    -
                                {% elif method.price_range.min_price == method.price_range.max_price %}
                                    {% gross method.price_range.min_price %}
                                {% else %}
                                    {% gross method.price_range.min_price %} -
                                    {% gross method.price_range.max_price %}
                                {% endif %}
                            </td>
                            <td>{{ method.countries|join:", " }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        {% include "dashboard/includes/_pagination.html" %}
    {% else %}
        <p>{% trans "No shipping methods found." %}</p>
    {% endif %}

{% endblock %}